// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetailerDisplay.Infrastructure.Persistence;

#nullable disable

namespace RetailerDisplay.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RetailerDisplayDbContext))]
    partial class RetailerDisplayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.AdminUser", b =>
                {
                    b.Property<long>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AdminUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AdminUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblAdminUser", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Content", b =>
                {
                    b.Property<long>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContentId"));

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<short>("ContentType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MasterKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaVariants")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("ContentId");

                    b.HasIndex("RetailerId");

                    b.ToTable("tblContent", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.ContentProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<long>("StoreProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StoreProductId");

                    b.HasIndex("ContentId", "StoreProductId")
                        .IsUnique();

                    b.ToTable("tblContentProduct", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeviceId"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .IsFixedLength();

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastSyncedVersion")
                        .HasColumnType("integer");

                    b.Property<short?>("Orientation")
                        .HasColumnType("smallint");

                    b.Property<long?>("PlaylistId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RefreshRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("integer");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceKey")
                        .IsUnique();

                    b.HasIndex("PlaylistId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("StoreId");

                    b.ToTable("tblDevice", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.DeviceStatusLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("LogId");

                    b.HasIndex("DeviceId", "ChangedAt");

                    b.ToTable("tblDeviceStatusLog", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.MasterProduct", b =>
                {
                    b.Property<long>("MasterProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MasterProductId"));

                    b.Property<decimal?>("Abv")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContainerType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("PackSize")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Upc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Vintage")
                        .HasColumnType("integer");

                    b.Property<string>("Volume")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MasterProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Upc")
                        .IsUnique();

                    b.ToTable("tblMasterProduct", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Playlist", b =>
                {
                    b.Property<long>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlaylistId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("PlaylistId");

                    b.HasIndex("RetailerId");

                    b.ToTable("tblPlaylist", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.PlaylistItem", b =>
                {
                    b.Property<long>("PlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlaylistItemId"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<short>("FitMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<long>("PlaylistId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistItemId");

                    b.HasIndex("ContentId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("tblPlaylistItem", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.ProductImport", b =>
                {
                    b.Property<long>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ImportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorReportUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.HasKey("ImportId");

                    b.HasIndex("RetailerId");

                    b.ToTable("tblProductImport", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TokenId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("tblRefreshToken", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Retailer", b =>
                {
                    b.Property<long>("RetailerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RetailerId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ProfileCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RetailerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblRetailer", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Store", b =>
                {
                    b.Property<long>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StoreId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StoreCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId");

                    b.HasIndex("RetailerId", "StoreCode")
                        .IsUnique();

                    b.ToTable("tblStore", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.StoreProduct", b =>
                {
                    b.Property<long>("StoreProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StoreProductId"));

                    b.Property<decimal?>("Abv")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContainerType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("ImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("MasterProductId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PackSize")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("RetailerId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<short>("Source")
                        .HasColumnType("smallint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Vintage")
                        .HasColumnType("integer");

                    b.Property<string>("Volume")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("StoreProductId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("MasterProductId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("StoreId", "Sku")
                        .IsUnique();

                    b.ToTable("tblStoreProduct", (string)null);
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Content", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Contents")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.ContentProduct", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Content", "Content")
                        .WithMany("ContentProducts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailerDisplay.Domain.Entities.StoreProduct", "StoreProduct")
                        .WithMany("ContentProducts")
                        .HasForeignKey("StoreProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("StoreProduct");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Device", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Devices")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Devices")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailerDisplay.Domain.Entities.Store", "Store")
                        .WithMany("Devices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Playlist");

                    b.Navigation("Retailer");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.DeviceStatusLog", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Device", "Device")
                        .WithMany("StatusLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Playlists")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.PlaylistItem", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Content", "Content")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailerDisplay.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.ProductImport", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("ProductImports")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Store", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Stores")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.StoreProduct", b =>
                {
                    b.HasOne("RetailerDisplay.Domain.Entities.ProductImport", "ImportBatch")
                        .WithMany("Products")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetailerDisplay.Domain.Entities.MasterProduct", "MasterProduct")
                        .WithMany("StoreProducts")
                        .HasForeignKey("MasterProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RetailerDisplay.Domain.Entities.Retailer", "Retailer")
                        .WithMany("Products")
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RetailerDisplay.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("MasterProduct");

                    b.Navigation("Retailer");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Content", b =>
                {
                    b.Navigation("ContentProducts");

                    b.Navigation("PlaylistItems");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Device", b =>
                {
                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.MasterProduct", b =>
                {
                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.ProductImport", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Retailer", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Devices");

                    b.Navigation("Playlists");

                    b.Navigation("ProductImports");

                    b.Navigation("Products");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.Store", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("RetailerDisplay.Domain.Entities.StoreProduct", b =>
                {
                    b.Navigation("ContentProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
