CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblMasterProduct" (
        "MasterProductId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Sku" character varying(80),
        "Upc" character varying(50),
        "ProductName" character varying(250) NOT NULL,
        "Description" text,
        "Category" character varying(120),
        "Brand" character varying(120),
        "ProductType" character varying(40),
        "Abv" numeric(4,2),
        "ContainerType" character varying(40),
        "Volume" character varying(30),
        "PackSize" integer,
        "Vintage" integer,
        "DefaultImageUrl" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblMasterProduct" PRIMARY KEY ("MasterProductId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblRetailer" (
        "RetailerId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(150) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "BusinessName" character varying(150) NOT NULL,
        "ContactName" character varying(120),
        "Phone" character varying(30),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblRetailer" PRIMARY KEY ("RetailerId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblContent" (
        "ContentId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "ContentType" smallint NOT NULL,
        "Name" character varying(150) NOT NULL,
        "MasterKey" character varying(500),
        "MediaVariants" jsonb,
        "ThumbnailKey" character varying(500),
        "DurationSeconds" integer,
        "FileSizeBytes" bigint,
        "ContentHash" character varying(64),
        "Version" integer NOT NULL DEFAULT 1,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblContent" PRIMARY KEY ("ContentId"),
        CONSTRAINT "FK_tblContent_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblPlaylist" (
        "PlaylistId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Version" integer NOT NULL DEFAULT 1,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblPlaylist" PRIMARY KEY ("PlaylistId"),
        CONSTRAINT "FK_tblPlaylist_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblProductImport" (
        "ImportId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "StoreId" bigint NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "TotalRows" integer NOT NULL,
        "SuccessCount" integer NOT NULL,
        "FailCount" integer NOT NULL,
        "Status" smallint NOT NULL,
        "ErrorReportUrl" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblProductImport" PRIMARY KEY ("ImportId"),
        CONSTRAINT "FK_tblProductImport_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblRefreshToken" (
        "TokenId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "TokenHash" character varying(256) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblRefreshToken" PRIMARY KEY ("TokenId"),
        CONSTRAINT "FK_tblRefreshToken_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblStore" (
        "StoreId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "StoreName" character varying(150) NOT NULL,
        "StoreCode" character varying(50),
        "AddressLine1" character varying(200),
        "AddressLine2" character varying(200),
        "City" character varying(100),
        "State" character varying(100),
        "PostalCode" character varying(20),
        "Country" character varying(100),
        "Latitude" numeric(9,6),
        "Longitude" numeric(9,6),
        "Phone" character varying(30),
        "Email" character varying(150),
        "TimeZone" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblStore" PRIMARY KEY ("StoreId"),
        CONSTRAINT "FK_tblStore_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblPlaylistItem" (
        "PlaylistItemId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PlaylistId" bigint NOT NULL,
        "ContentId" bigint NOT NULL,
        "SortOrder" integer NOT NULL,
        "DurationSeconds" integer,
        "FitMode" smallint NOT NULL DEFAULT 1,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblPlaylistItem" PRIMARY KEY ("PlaylistItemId"),
        CONSTRAINT "FK_tblPlaylistItem_tblContent_ContentId" FOREIGN KEY ("ContentId") REFERENCES "tblContent" ("ContentId") ON DELETE RESTRICT,
        CONSTRAINT "FK_tblPlaylistItem_tblPlaylist_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "tblPlaylist" ("PlaylistId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblDevice" (
        "DeviceId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "StoreId" bigint,
        "DeviceKey" character(8) NOT NULL,
        "DeviceName" character varying(120),
        "PlaylistId" bigint,
        "Orientation" smallint,
        "ScreenWidth" integer,
        "ScreenHeight" integer,
        "AppVersion" character varying(30),
        "LastSeenAt" timestamp with time zone,
        "LastSyncedVersion" integer,
        "RefreshRequested" boolean NOT NULL DEFAULT FALSE,
        "IsRevoked" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblDevice" PRIMARY KEY ("DeviceId"),
        CONSTRAINT "FK_tblDevice_tblPlaylist_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "tblPlaylist" ("PlaylistId") ON DELETE SET NULL,
        CONSTRAINT "FK_tblDevice_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT,
        CONSTRAINT "FK_tblDevice_tblStore_StoreId" FOREIGN KEY ("StoreId") REFERENCES "tblStore" ("StoreId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblStoreProduct" (
        "StoreProductId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RetailerId" bigint NOT NULL,
        "StoreId" bigint NOT NULL,
        "MasterProductId" bigint,
        "Source" smallint NOT NULL,
        "Sku" character varying(80) NOT NULL,
        "ProductName" character varying(250) NOT NULL,
        "Description" text,
        "Category" character varying(120),
        "Brand" character varying(120),
        "ProductType" character varying(40),
        "Abv" numeric(4,2),
        "ContainerType" character varying(40),
        "Volume" character varying(30),
        "PackSize" integer,
        "Vintage" integer,
        "Price" numeric(10,2) NOT NULL,
        "SalePrice" numeric(10,2),
        "Currency" character(3) NOT NULL DEFAULT 'USD',
        "ImageUrl" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "ImportBatchId" bigint,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblStoreProduct" PRIMARY KEY ("StoreProductId"),
        CONSTRAINT "FK_tblStoreProduct_tblMasterProduct_MasterProductId" FOREIGN KEY ("MasterProductId") REFERENCES "tblMasterProduct" ("MasterProductId") ON DELETE SET NULL,
        CONSTRAINT "FK_tblStoreProduct_tblProductImport_ImportBatchId" FOREIGN KEY ("ImportBatchId") REFERENCES "tblProductImport" ("ImportId") ON DELETE SET NULL,
        CONSTRAINT "FK_tblStoreProduct_tblRetailer_RetailerId" FOREIGN KEY ("RetailerId") REFERENCES "tblRetailer" ("RetailerId") ON DELETE RESTRICT,
        CONSTRAINT "FK_tblStoreProduct_tblStore_StoreId" FOREIGN KEY ("StoreId") REFERENCES "tblStore" ("StoreId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblDeviceStatusLog" (
        "LogId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "DeviceId" bigint NOT NULL,
        "Status" smallint NOT NULL,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblDeviceStatusLog" PRIMARY KEY ("LogId"),
        CONSTRAINT "FK_tblDeviceStatusLog_tblDevice_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES "tblDevice" ("DeviceId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE TABLE "tblContentProduct" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ContentId" bigint NOT NULL,
        "StoreProductId" bigint NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_tblContentProduct" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_tblContentProduct_tblContent_ContentId" FOREIGN KEY ("ContentId") REFERENCES "tblContent" ("ContentId") ON DELETE CASCADE,
        CONSTRAINT "FK_tblContentProduct_tblStoreProduct_StoreProductId" FOREIGN KEY ("StoreProductId") REFERENCES "tblStoreProduct" ("StoreProductId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblContent_RetailerId" ON "tblContent" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblContentProduct_ContentId_StoreProductId" ON "tblContentProduct" ("ContentId", "StoreProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblContentProduct_StoreProductId" ON "tblContentProduct" ("StoreProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblDevice_DeviceKey" ON "tblDevice" ("DeviceKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblDevice_PlaylistId" ON "tblDevice" ("PlaylistId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblDevice_RetailerId" ON "tblDevice" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblDevice_StoreId" ON "tblDevice" ("StoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblDeviceStatusLog_DeviceId_ChangedAt" ON "tblDeviceStatusLog" ("DeviceId", "ChangedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblMasterProduct_Sku" ON "tblMasterProduct" ("Sku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblMasterProduct_Upc" ON "tblMasterProduct" ("Upc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblPlaylist_RetailerId" ON "tblPlaylist" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblPlaylistItem_ContentId" ON "tblPlaylistItem" ("ContentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblPlaylistItem_PlaylistId" ON "tblPlaylistItem" ("PlaylistId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblProductImport_RetailerId" ON "tblProductImport" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblRefreshToken_RetailerId" ON "tblRefreshToken" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblRefreshToken_TokenHash" ON "tblRefreshToken" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblRetailer_Email" ON "tblRetailer" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblStore_RetailerId_StoreCode" ON "tblStore" ("RetailerId", "StoreCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblStoreProduct_ImportBatchId" ON "tblStoreProduct" ("ImportBatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblStoreProduct_MasterProductId" ON "tblStoreProduct" ("MasterProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE INDEX "IX_tblStoreProduct_RetailerId" ON "tblStoreProduct" ("RetailerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tblStoreProduct_StoreId_Sku" ON "tblStoreProduct" ("StoreId", "Sku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716103141_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716103141_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716165015_AddAdminUser') THEN
    CREATE TABLE "tblAdminUser" (
        "AdminUserId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(150) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "Name" character varying(120),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_tblAdminUser" PRIMARY KEY ("AdminUserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716165015_AddAdminUser') THEN
    CREATE UNIQUE INDEX "IX_tblAdminUser_Email" ON "tblAdminUser" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716165015_AddAdminUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716165015_AddAdminUser', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "AddressLine1" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "AddressLine2" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "City" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "Country" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "PostalCode" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "ProfileCompleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    ALTER TABLE "tblRetailer" ADD "State" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716172532_AddRetailerProfileFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716172532_AddRetailerProfileFields', '8.0.11');
    END IF;
END $EF$;
COMMIT;

